CURRENT_MODEL_TYPE: CPKT
TORCH:
  model_path: /root/model_deployment/model_file/torch_model/model.pt
  model_graph_file_path: /root/model_deployment/model_file/torch_model/torch_network.py
CPKT:
  model_directory: /root/model_deployment/model_file/mymodels
  model_graph_file_path: /root/model_deployment/model_file/mymodels/mnist.cpkt.meta
  input_node_name: mnist_image
  output_node_name: result
PB:
  model_path: /root/model_deployment/model_file/mnist_model.pb
  input_node_name: ~
  output_node_name: ~
H5:
  model_path: /root/model_deployment/model_file/mymodel.h5
